version: '1'
services:
  moveo:
    build: .
    command: tail -F anything
    ports:
      - "5901:5901"
    environment:
      - VNC_RESOLUTION=1280x720
      - VNC_PASSWORD=mypassword
      - DISPLAY=host.docker.internal:0.0
      - LIBGL_ALWAYS_INDIRECT=0
      - GAZEBO_IP=127.0.0.1